# Generated by Django 4.0.3 on 2022-06-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_alter_usuario_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='prueba',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='correo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_name',
            field=models.TextField(blank=True, max_length=150, verbose_name='Apellidos'),
        ),
    ]
