# Generated by Django 4.0.3 on 2022-06-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datosUsuarioInstagram', '0003_alter_idsesionusuario_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idsesionusuario',
            name='content',
            field=models.TextField(),
        ),
    ]
