# Generated by Django 4.0.3 on 2022-06-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datosUsuarioInstagram', '0005_remove_idsesionusuario_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idsesionusuario',
            name='id',
            field=models.BigAutoField(auto_created=True, default=2232, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='idsesionusuario',
            name='content',
            field=models.TextField(),
        ),
    ]
