# Generated by Django 4.0.3 on 2022-06-16 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datosUsuarioInstagram', '0006_idsesionusuario_id_alter_idsesionusuario_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idsesionusuario',
            options={'ordering': ['-add_fecha'], 'verbose_name': 'IDSesionUsuario', 'verbose_name_plural': 'IDSesionUsuarios'},
        ),
        migrations.AddField(
            model_name='idsesionusuario',
            name='add_fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='idsesionusuario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
