# Generated by Django 4.0.3 on 2022-07-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datosUsuarioInstagram', '0010_busquedausuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busquedausuario',
            name='id',
        ),
        migrations.RemoveField(
            model_name='busquedausuario',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='busquedausuario',
            name='IDusuario',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
