# Generated by Django 4.0.3 on 2022-07-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datosUsuarioInstagram', '0011_remove_busquedausuario_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busquedausuario',
            name='nombre',
            field=models.TextField(blank=True),
        ),
    ]
