# Generated by Django 4.0.3 on 2022-07-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datosUsuarioInstagram', '0012_busquedausuario_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosBusquedaUsuario',
            fields=[
                ('IDcuenta', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Nombre', models.TextField(blank=True)),
                ('Usuario_verificado', models.BooleanField()),
                ('Popularidad', models.IntegerField()),
                ('Perfil', models.TextField()),
                ('Usuario_privado', models.BooleanField()),
                ('Cuenta_negocios', models.BooleanField()),
                ('Publicaciones', models.IntegerField()),
                ('Biografia', models.TextField()),
                ('Foto_perfil', models.TextField()),
                ('Website', models.TextField()),
                ('Videos', models.IntegerField()),
                ('mediaLikesPostRecientes', models.FloatField()),
                ('mediaComentariosPostRecientes', models.FloatField()),
                ('mediaLikesVideos', models.FloatField()),
                ('mediaComentariosVideos', models.FloatField()),
                ('mediaVisualizacionesVideos', models.FloatField()),
                ('mediaLikesPublicacionesEtiquetadas', models.FloatField()),
                ('mediaComentariosPublicacionesEtiquetadas', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='BusquedaUsuario',
        ),
    ]
