# Generated by Django 4.0.3 on 2022-07-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datosUsuarioInstagram', '0013_datosbusquedausuario_delete_busquedausuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosbusquedausuario',
            name='Website',
            field=models.TextField(null=True),
        ),
    ]
