# Generated by Django 4.0.3 on 2022-07-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datosUsuarioInstagram', '0014_alter_datosbusquedausuario_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosbusquedausuario',
            name='Website',
            field=models.TextField(blank=True, null=True),
        ),
    ]
