# Generated by Django 4.0.3 on 2022-07-22 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datosUsuarioInstagram', '0015_alter_datosbusquedausuario_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosbusquedausuario',
            name='Biografia',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='datosbusquedausuario',
            name='Foto_perfil',
            field=models.TextField(blank=True),
        ),
    ]
