# Generated by Django 4.0.3 on 2022-07-23 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datosUsuarioInstagram', '0016_alter_datosbusquedausuario_biografia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosVideosBusquedaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reproducciones', models.IntegerField()),
                ('likes', models.IntegerField()),
                ('comentarios', models.IntegerField()),
                ('fecha', models.CharField(max_length=20)),
                ('url', models.TextField()),
                ('cuentaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datosUsuarioInstagram.datosbusquedausuario')),
            ],
        ),
        migrations.CreateModel(
            name='DatosPostBusquedaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField()),
                ('comentarios', models.IntegerField()),
                ('tipo', models.CharField(max_length=20)),
                ('fecha', models.CharField(max_length=20)),
                ('url', models.TextField()),
                ('cuentaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datosUsuarioInstagram.datosbusquedausuario')),
            ],
        ),
        migrations.CreateModel(
            name='DatosEtiquetadasBusquedaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField()),
                ('comentarios', models.IntegerField()),
                ('tipo', models.CharField(max_length=20)),
                ('fecha', models.CharField(max_length=20)),
                ('url', models.TextField()),
                ('cuentaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datosUsuarioInstagram.datosbusquedausuario')),
            ],
        ),
    ]
