# Generated by Django 4.0.3 on 2022-07-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datosUsuarioInstagram', '0018_alter_datospostbusquedausuario_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosetiquetadasbusquedausuario',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='datosvideosbusquedausuario',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
