# Generated by Django 4.0.3 on 2022-07-25 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datosUsuarioInstagram', '0019_alter_datosetiquetadasbusquedausuario_fecha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDusuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuarioID', models.IntegerField()),
                ('cuentaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datosUsuarioInstagram.datosbusquedausuario')),
            ],
        ),
    ]
