# Generated by Django 4.0.3 on 2022-07-25 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datosUsuarioInstagram', '0020_idusuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IDusuario',
            new_name='IdentificadorUsuario',
        ),
        migrations.AlterModelOptions(
            name='datosetiquetadasbusquedausuario',
            options={'verbose_name': 'Datos post etiquetados busqueda de usuario'},
        ),
        migrations.AlterModelOptions(
            name='identificadorusuario',
            options={'verbose_name': 'ID usuario'},
        ),
    ]
