# Generated by Django 4.0.3 on 2022-07-27 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datosUsuarioInstagram', '0021_rename_idusuario_identificadorusuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosHighlight',
            fields=[
                ('identificador_highlight_usuario', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=30)),
                ('numero_historias', models.IntegerField()),
                ('foto_portada', models.TextField()),
                ('url', models.TextField()),
                ('numeroImagenes', models.IntegerField()),
                ('numeroVideos', models.IntegerField()),
                ('cuentaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datosUsuarioInstagram.datosbusquedausuario')),
            ],
            options={
                'verbose_name': 'Highlight',
            },
        ),
        migrations.CreateModel(
            name='DatosStoryHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField()),
                ('duracion', models.FloatField()),
                ('url', models.TextField()),
                ('highlight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datosUsuarioInstagram.datoshighlight')),
            ],
            options={
                'verbose_name': 'Historias highlight',
            },
        ),
        migrations.CreateModel(
            name='ContadorHighlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contadorHighlights', models.IntegerField()),
                ('cuentaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datosUsuarioInstagram.datosbusquedausuario')),
            ],
            options={
                'verbose_name': 'Contador highlights cuenta',
            },
        ),
    ]
