# Generated by Django 4.0.3 on 2022-07-29 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datosUsuarioInstagram', '0024_alter_identificadorusuario_cuentaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contadorhighlights',
            name='cuentaID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datosUsuarioInstagram.datosbusquedausuario'),
        ),
    ]
