# Generated by Django 4.0.3 on 2022-07-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datosUsuarioInstagram', '0025_alter_contadorhighlights_cuentaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosetiquetadasbusquedausuario',
            name='shortcode',
            field=models.CharField(default='abc', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datospostbusquedausuario',
            name='shortcode',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='datosvideosbusquedausuario',
            name='shortcode',
            field=models.CharField(default='abc', max_length=50),
            preserve_default=False,
        ),
    ]
