# Generated by Django 4.0.3 on 2022-07-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datosUsuarioInstagram', '0026_datosetiquetadasbusquedausuario_shortcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospostbusquedausuario',
            name='shortcode',
            field=models.CharField(max_length=50),
        ),
    ]
