# Generated by Django 4.0.3 on 2022-08-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datosUsuarioInstagram', '0027_alter_datospostbusquedausuario_shortcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosbusquedausuario',
            name='numeroImagenesPostRecientes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datosbusquedausuario',
            name='numeroImagenesPublicacionesEtiquetadas',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datosbusquedausuario',
            name='numeroSidecarsPostRecientes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datosbusquedausuario',
            name='numeroSidecarsPublicacionesEtiquetadas',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datosbusquedausuario',
            name='numeroVideosPostRecientes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datosbusquedausuario',
            name='numeroVideosPublicacionesEtiquetadas',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datosetiquetadasbusquedausuario',
            name='shortcode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datospostbusquedausuario',
            name='shortcode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='datosvideosbusquedausuario',
            name='shortcode',
            field=models.CharField(max_length=100),
        ),
    ]
