# Generated by Django 4.0.3 on 2022-08-06 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datosUsuarioInstagram', '0030_datospost_usuariosetiquetadospost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaScrapeoInstagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.CharField(max_length=100)),
                ('usando', models.BooleanField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta Scrapeo Instagram',
                'verbose_name_plural': 'Cuentas Scrapeo Instagram',
                'ordering': ['-fecha'],
            },
        ),
    ]
