# Generated by Django 4.0.3 on 2022-08-08 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datosUsuarioInstagram', '0031_cuentascrapeoinstagram'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IDSesionUsuario',
        ),
    ]
